version: "3.9"

services:
  db:
    image: mysql:8
    container_name: silostrat-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: silostrat
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"

  backend:
    build: ./backend
    command: npm run start:dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_URL: mysql://root:root@db:3306/silostrat
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
